# Generated by Django 4.2.6 on 2023-10-21 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CER2.entidad')),
            ],
        ),
    ]
