# Generated by Django 4.2.6 on 2023-10-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CER2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='titulo',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='entidad',
            name='nombre',
            field=models.CharField(default='default', max_length=30),
        ),
    ]
