# Generated by Django 4.2.6 on 2023-10-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CER2', '0002_comunicado_titulo_entidad_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='detalle',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='detalle_corto',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='modificado_por',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='publicado_por',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entidad',
            name='logo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
